### ISSUE TITLE
Lombok's @Data annotation not working with Spring Boot 3 [BUG] 

### ISSUE THREAD

**Issue by lohitakshay35** [projectlombok/lombok#3493]
I upgraded my spring boot project from 2.3 to 3.1 , I do not get any red markers in my code,but when I try to build the project, I get these errors:
![image](https://github.com/projectlombok/lombok/assets/49298833/2a5ca50d-6c66-477e-8051-615f93340de8)

Lombok works in STS:
![image](https://github.com/projectlombok/lombok/assets/49298833/a0e94be4-ca87-4be9-a352-56ad141839aa)

The build works upto spring boot version 3, but when I change it to 3, These errors pop up. But when I manually type in the getters and setters, the errors go away. Is there any fix to this?

![image](https://github.com/projectlombok/lombok/assets/49298833/3930a0b9-51cf-49df-97d6-2cb78b7adbda)

**Comment by lohitakshay35** [comment]
@Rawi01 The lombok dependency for maven is 1.18.28 aswell. Thanks for the reply tho.

**Comment by Rawi01** [comment]
You get this long list of errors because the compiler does not trigger the lombok annotation processing. In most cases the build setup is wrong or the lombok version does not support the used `javac` version.

In some cases the compiler detect some error cases and aborts the compilation process but still run the normal error detection. To see the real error you have to set `-Xmaxerrs` to increase the amount of errors the compiler prints. One known problem during the migration is the `@ConstructorBinding` annotation (see #3331)

**Comment by lohitakshay35** [comment]
@Rawi01 I'm using Java 17 and lombok 1.18.28, so I guess this lombok version supports this java version (I've also used the previous versions of lambok aswell). And by using `-Xmaxerrs` I get only the setter and getter methods as errors. I've checked for `@ConstructorBinding`, but I haven't used it in my code.  I can't figure out what is causing this issue.

**Comment by lohitakshay35** [comment]
One thing to mention is that I've built another Spring Boot 3 project and lombok works fine there(Build Successful), so I guess the compiler triggers the lombok annotation processing.

**Comment by Rawi01** [comment]
If you have another project with an identical build setup, it's obviously not a lombok-specific problem. When setting `-Xmaxerrs`, you must also specify a maximum number of errors to output.

Alternatively you can try the experimental compiler plugin which is linked in #3331.

**Comment by lohitakshay35** [comment]
Hey how do i use this compiler plugin in my project?

**Comment by kkaarrss** [comment]
Hi, @lohitakshay35 did you manage to come closer to solving this issue? I have been facing the same issue after upgrading to Spring Boot  3 and have not been able to solve this. Another project with the same versions builds perfectly fine and I do not see any difference that could explain it.

**Comment by kajh** [comment]
We too has an issue with this after upgrading from Spring Boot 2.7.x to 3.1.x. The source of the problem in our case was another compilation error from a change in Spring. After fixing that error the Lombok releated compilation error disappeared.

**Comment by lohitakshay35** [comment]
@kkaarrss as @kajh said, We too had another compilation error (had MappedSuperClass import error, from Spring Boot 3 we have to use Jakarta but for some reason this caused an error and I had to change it back to Javax) and this solved my Lombok errors.

**Comment by dezmans** [comment]
My feedback on this same issue . . . was playing around with [SpringBood 3.2 and zulu64-17.x jdk] some code and ran into this head scratcher . . . did everything right. But I was forced to autogenerate getters/headers the old fashion way, just to get it to run against my JpaRepository over hibernate to Oracle DB. 

So none of the recommendations, good ones, seem to work. [;~{>

So I left it . . . recently I got back to it . . . I noticed a simple warning which was about the Entity:

public class myEntity implements Serializable 
{     
       //========================
       //this was missing from my Entity
       //========================
	private static final long serialVersionUID = 100001L;
	
	Then boom!! ==> all the other warnings started to go away with simple modifications, even got rid of the hard-coded getters and setters.

These annotations started to work !!
@Data
@NoArgsConstructor
@Slf4j

Oddly enough, I cannot longer reproduce, something got kicked in the head on this once Lombok-deprived project.

**Comment by Rawi01** [comment]
The problem is always a different compilation problem that breaks annotation processing in the compiler. The two proven solutions to find the actual problem (`-Xmaxerrs`, compiler plugin) were posted above. You can also try to use the eclipse compiler, fix the real problem and switch back to `javac`.

**Comment by kkaarrss** [comment]
Thanks, in the end I reverted back and migrated in smaller steps. I have not encountered the same error since. So indeed it was very well possible that another error was causing it.

**Comment by ArunChandrashekar** [comment]
Download lombak.jar

In eclipse.ini file (located in your Eclipse installation directory) add the following line:
-javaagent:D:\software local\lombok.jar

**Comment by selimppc** [comment]
In the new version of `Spring Boot 3.x.x`,  `spring-boot-maven-plugin` configuration explicitly excludes Lombok.

I had the same issue in the version of `Spring boot 3.4.0`. I solved the issue by removing the `spring-boot-maven-plugin`  from my `pom.xml`:

see my configuration (pom.xml):

```
    <build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<annotationProcessorPaths>
						<path>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
						</path>
					</annotationProcessorPaths>
				</configuration>
			</plugin>
		</plugins>
	</build>
```

and the Entity:

```
import lombok.*;

@Data
public class Tag {
    private Long id;
    private String name;
}
```

Result:

    $ mvn clean install

    ....
    [INFO] ---------------------------------------------------------------
    [INFO] BUILD SUCCESS
    [INFO] ---------------------------------------------------------------

**Comment by hv-ojha** [comment]
I was facing the similar issue. Everything seems perfect in my code but there was an issue with Intellij IDE. So I followed these steps.

Go to Files -> Settings -> Build, Execution, Deployment -> Compiler -> Annotation Processor -> appName -> Select `Obtain processor from project classpath` option.

![Screenshot 2024-12-21 180507](https://github.com/user-attachments/assets/09d1e9c1-1680-4479-a9ae-31ae1be0e2f3)

**Comment by Adel1818** [comment]
@kajh hv-ojha

worked for me : build, run and test api => ok 
but i sill get notifications errors
![image](https://github.com/user-attachments/assets/796549fa-ce81-4b0b-865f-5fe956f63e78)

**Comment by akmal09** [comment]
This happen when i use version 3.4.1, the solution is downgrade the version of the spring boot to become 3.4.0 or 3.3.x

**Comment by makucg** [comment]
> This happen when i use version 3.4.1, the solution is downgrade the version of the spring boot to become 3.4.0 or 3.3.x

Thanks

**Comment by harsav360** [comment]
This worked for me

<annotationProcessorPaths>
    <path>
        <groupId>org.projectlombok</groupId>
        <artifactId>lombok</artifactId>
        <version>1.18.36</version>
    </path>
</annotationProcessorPaths>

**Comment by harsav360** [comment]
This worked for me 

<annotationProcessorPaths>
    <path>
        <groupId>org.projectlombok</groupId>
        <artifactId>lombok</artifactId>
        <version>1.18.36</version>
    </path>
</annotationProcessorPaths>

**Comment by harsav360** [comment]
This worked for me. 

`
<annotationProcessorPaths>
    <path>
        <groupId>org.projectlombok</groupId>
        <artifactId>lombok</artifactId>
        <version>1.18.36</version>
    </path>
</annotationProcessorPaths>
`

**Comment by LennyLee1998** [comment]
I solved that issue by using maven 's lifecycle: clean & install, after that, the .class file had the constructor
