### ISSUE TITLE
[BUG] Autocomplete for `val` variables stops working "randomly" in Eclipse

### ISSUE THREAD

**Issue by pbodnar** [projectlombok/lombok#3440]
**Describe the bug**

In Eclipse 4.27+ with Lombok 1.18.27+, recognizing the type of `val`-defined variables and then also logically autocomplete of their members stops working "randomly" (described below). The code _compiles_ fine, Eclipse shows no compilation errors, yet it shows that the given variable defined via `val` is a plain `Object`. And sometimes it is even "stuck in the middle": the type is displayed correctly, yet autocomplete lists only `Object` members.

It is basically the same problem as described at redhat-developer/vscode-java/issues/2983 ([this](https://user-images.githubusercontent.com/34871211/223144302-7d4426ae-8d21-486a-8392-08111979b1a7.png)) with the following differences:

* It happens in Eclipse.
* It happens even after upgrading Lombok to 1.18.27 (edge release) or 1.18.28 (upgraded because of the support for `lombok.config` - see #3332).
* It happens seemingly _randomly_.

No errors seen in Eclipse logs which could point to the problem.

**To Reproduce**

It seems like the problem can be reproduced on this minimal example Java code:

```java
import lombok.val;

public class LombokExample {

    protected String breakVal = "anything";

    public void main(String[] args) {
        val num = String.valueOf(args.length);
        // num wrongly shown as Object if breakVal field is initiated within its declaration
        System.out.println(num.charAt(0));
    }
}
```

Steps to reproduce:

0. Close all editors in Eclipse. (purely optional - one can just leave either A, or B from step 2 focused)
1. Restart Eclipse.
2. As the first editor open:
    A: the class above (or seemingly any class which doesn't use `val`) - breaks!
    B: a class which uses `val`, but doesn't use any field initializers - doesn't break!

Note that when the functionality breaks, it breaks _globally_ - i.e. it affects editing of Java classes from completely unrelated projects. Until another Eclipse restart.

**Expected behavior**

Eclipse should recognize and show proper `val` variable type _all the time_.

**Version info (please complete the following information):**

 - Lombok version: 1.18.27 and 1.18.28 (and with Lombok 1.28.24, it gets even worse: `Object` is _always_ shown for a `val` variable)
 - Platform: Windows 10, javac 11.0.18, Eclipse 2023-03 (4.27.0) and 2023-06 (4.28.0) (both "Eclipse IDE for Enterprise Java and Web Developers")

**Workaround**

As described above, it looks like the issue can be avoided by always firstly opening a class (`*.java`) with `val` but without any field initializers when (re)starting Eclipse.

**Comment by Rawi01** [comment]
"Random" behaviour is always hard to debug, can you give an example file where this problem occurs? The linked issue was caused by additional `var` imports and is already fixed.

**Comment by pbodnar** [comment]
@Rawi01, yeah, I know. I will try to prepare some example.

Anyway, there is no usage import of `lombok.var` or `lombok.*` in the projects. BTW [the last comment](https://github.com/redhat-developer/vscode-java/issues/2983#issuecomment-1486655037) at the linked issues says the issue got resolved by #3332, so I'm a little bit confused in this regard.

**Comment by pbodnar** [comment]
Finally, I think I've got a repro! 🎉 It looks like the functionality breaks once I: 1) add a Java file / class which overrides a class from a project dependency, 2) AND restart Eclipse. If it helps, I can share the concrete example Maven project then, it will take just a while to push it to GitHub...

**Comment by pbodnar** [comment]
I've played with it more and here are probably **the final reproduction steps** (which also happen to explain the "randomness" of the issue manifestation):

0. Close all editors in Eclipse. (purely optional - one can just leave either A, or B from step 2 focused)
1. Restart Eclipse.
2. As the first editor open:
A: the problematic (overriding) class - breaks!
B: another (non-overriding) class - doesn't break!

Also note that when the functionality breaks, it breaks _globally_ - i.e. it affects editing of Java classes from completely unrelated projects.

Some ideas what can cause this then? As just described, it seems to be all about _the first Java class being opened in Eclipse after its start_.

**Comment by pbodnar** [comment]
OK, so here comes the MRE (pretty artificial one, I know ;)):

```java
import lombok.val;

public class LombokExample {

    protected String breakVal = "anything";

    public void main(String[] args) {
        val num = String.valueOf(args.length);
        // num wrongly shown as Object if breakVal field is initiated within its declaration
        System.out.println(num.charAt(0));
    }
}
```

I.e. no need to override a class from a project dependency as I guessed above. Instead, simply having a class field initialized breaks the functionality.

Can you please check? It seems weird that I would be the only one or the first with this problem...

**Comment by Rawi01** [comment]
Thanks for the reproducer. I just tried this and `num` is still a `String` but the autocomplete only shows `Object` methods.

**Comment by Rawi01** [comment]
Seems to be a weird classloading issue...

**Comment by pbodnar** [comment]
@Rawi01, thank you for looking at it.

It looks like the problem existed even in Lombok 1.18.24 - I've just tried to set it for the new Eclipse, taking the same reproduction steps and Eclipse shows `Object` for `num` even if I there is no field in the example class. So the newer Lombok versions seem to fix the problem (there was some playing with classloaders in the latest commits), but only partially...

**Comment by pbodnar** [comment]
@all, based on the findings above, I've adjusted the issue description - added the steps to reproduce and the workaround steps.

**Comment by Rawi01** [comment]
Can you try if the linked commit fixes the problem? You can download the compiled jar here: https://github.com/Rawi01/lombok/suites/14848496959/artifacts/845564771

**Comment by pbodnar** [comment]
@Rawi01, unfortunately I'm getting StackOverflowError with the lombok.jar you have shared, no matter what class I open firstly in Eclipse 2023-06 (4.28.0):

```
java.lang.StackOverflowError
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.overrideLoadResult(ModuleClassLoader.java:55)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at lombok.launch.ShadowClassLoader.<init>(ShadowClassLoader.java:108)
	at jdk.internal.reflect.GeneratedConstructorAccessor5.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.overrideLoadResult(ModuleClassLoader.java:132)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at lombok.launch.ShadowClassLoader.<init>(ShadowClassLoader.java:108)
        ...
```

Of course, I don't quite understand all the magic stuff done by Lombok, but are you sure about the commit message `... Prepend jdt.core classloader to the parser`? It looks to me, the jdt.core classloader was already prepended somewhere, but maybe _in a different fashion_?

**Comment by Rawi01** [comment]
Thanks for testing, the recent changes for #3474 broke the eclipse plugin and I rebased my branch before I pushed it and was not aware of that...

Lombok usually runs after the parser and requires a bunch of other eclipse classes to do its stuff. A few versions ago the eclipse compiler was moved into its own OSGi module which makes it impossible to read the eclipse classes. Instead of rewriting everything I added the classloader of the core module to the compiler module classloader (#3347). This worked in some cases but it turns out that the initialization order in eclipse is different if there is an open file or not. I fixed that too (#3411). The whole prepend stuff happens after the first parse but if the class contains some features (e.g. `val`) some lombok classes get loaded before the parse ends and these classes are unable to find the eclipse stuff. Thats what causes this issue. I fixed that by prepending the classloader after the parser class gets initialized. 

The commit message is not really well worded, sorry for that.

**Comment by pbodnar** [comment]
@Rawi01, thanks for the additional explanation, I think I can understand the issue and its evolution a bit now. :)

So the blocker issue introduced by #3474 will be hopefully resolved soon (even though I cannot see any continuation agenda for fixing it - yet?) and we can do another testing round afterwards?

**Comment by rzwitserloot** [comment]
Hi team. Whooooops, my bad. A combination of a bizarre bug that affected me but few others, when I installed a nightly build into my eclipse it didn't do anything which meant I was 'blind' to a bug in the package shader code that broke eclipse entirely.

That is fixed now: The current state of the main branch now works fine again. @Rawi01 and @pbodnar: Continue with the good work on fixing __this__ bug and my apologies for getting in your way by messing up the eclipse agent on main branch.

**Comment by Rawi01** [comment]
@pbodnar Rebased and pushed my branch, please try if the updated version (https://github.com/Rawi01/lombok/actions/runs/6202448200) works for you.

**Comment by pbodnar** [comment]
@Rawi01, I can confirm the updated Lombok version works for me, both in Eclipse 2023-06 and 2023-09. Thank you and looking forward to the new release! 🥳
