### PR TITLE
Introduce `--source` argument for Delombok

### LINKED ISSUE #3025: [BUG] val keyword delombok result breaks with Java 7 compatibility
This code after delombok builds fine with 1.18.20, but breaks with 1.18.22:
```java
package org.projectlombok.test;

import lombok.val;
import org.junit.Assert;
import org.junit.Test;

public class DataExampleTest {
    @Test
    public void testDataExample() {
        val name = "MyData";
        val de = new DataExample(name);
        Assert.assertEquals(de.getName(), name);
    }
}
```
I have source & target set to 1.7 for the compiler plugin, but my Javac is 17.  The delombok code looks like:
```java
// Generated by delombok at Sun Oct 31 06:58:48 PDT 2021
package org.projectlombok.test;

import org.junit.Assert;
import org.junit.Test;

public class DataExampleTest {
    @Test
    public void testDataExample() {
        final var name = "MyData";
        final var de = new DataExample(name);
        Assert.assertEquals(de.getName(), name);
    }
}
```
The error is:
```
[ERROR] /Users/anthony/github/awhitford/lombok.maven/test-maven-lombok/target/generated-test-sources/delombok/org/projectlombok/test/DataExampleTest.java:[10,15] cannot find symbol
[ERROR]   symbol:   class var
[ERROR]   location: class org.projectlombok.test.DataExampleTest
[ERROR] /Users/anthony/github/awhitford/lombok.maven/test-maven-lombok/target/generated-test-sources/delombok/org/projectlombok/test/DataExampleTest.java:[11,15] cannot find symbol
[ERROR]   symbol:   class var
[ERROR]   location: class org.projectlombok.test.DataExampleTest
```

Previously the output would be:
```java
// Generated by delombok at Fri Apr 02 06:02:09 UTC 2021
package org.projectlombok.test;

import org.junit.Assert;
import org.junit.Test;

public class DataExampleTest {
    @Test
    public void testDataExample() {
        final java.lang.String name = "MyData";
        final org.projectlombok.test.DataExample de = new DataExample(name);
        Assert.assertEquals(de.getName(), name);
    }
}
```

Based on the [change log](https://projectlombok.org/changelog), I thought that the `val` conversion to `final var` was limited to when the compiler source option is 10 or higher.

**Version info (please complete the following information):**
 - Lombok version 1.18.22
 - Platform: OpenJDK 17
 ```
Apache Maven 3.8.3 (ff8e977a158738155dc465c6a97ffaf31982d739)
Maven home: /usr/local/Cellar/maven/3.8.3/libexec
Java version: 17, vendor: Homebrew, runtime: /usr/local/Cellar/openjdk/17/libexec/openjdk.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "11.6", arch: "x86_64", family: "mac"
```

### PR DESCRIPTION
**Pull request by tamasvajk**
This PR introduces the a optional `--source` argument for Delombok. By specifying `--source=X`, the generated output conforms to Java version X. `val x = 1;` is Delomboked to `final var x = 1;` or `final int x = 1;` depending on the JVM executing Delombok. Specifying `--source=1.8` results in the latter `final int x = 1;` variant even on JVM above version 9.

Fixes https://github.com/projectlombok/lombok/issues/3025.

### CODE REVIEW

**Comment by rzwitserloot** [comment]
Lovely idea and we'll pick this up soon.
