### ISSUE TITLE
[BUG] Netbeans IDE throws Lombok related exeption

### ISSUE THREAD

**Issue by makiam** [projectlombok/lombok#3928]
**Describe the bug**
Once I opened Lombok annotated file I see an exception in Netbeans IDE log:
java.lang.AbstractMethodError: Receiver class lombok.javac.Javac$JavadocOps_8$1 does not define or inherit an implementation of the resolved method 'abstract com.sun.tools.javac.parser.Tokens$Comment stripIndent()' of interface com.sun.tools.javac.parser.Tokens$Comment.
	at com.sun.tools.javac.parser.DocCommentParser.<init>(DocCommentParser.java:168)
	at com.sun.tools.javac.parser.DocCommentParser.<init>(DocCommentParser.java:146)
	at com.sun.tools.javac.api.JavacTrees.getDocCommentTree(JavacTrees.java:1133)
	at com.sun.tools.javac.parser.LazyDocCommentTable.getCommentTree(LazyDocCommentTable.java:101)
	at com.sun.tools.javac.api.JavacTrees.getDocCommentTree(JavacTrees.java:758)
	at org.netbeans.modules.java.editor.base.javadoc.JavadocImports.computeReferencedElements(JavadocImports.java:110)
	at org.netbeans.modules.java.editor.base.imports.UnusedImports$DetectorVisitor.handleJavadoc(UnusedImports.java:137)
	at org.netbeans.modules.java.editor.base.imports.UnusedImports$DetectorVisitor.visitVariable(UnusedImports.java:183)
	at org.netbeans.modules.java.editor.base.imports.UnusedImports$DetectorVisitor.visitVariable(UnusedImports.java:112)
	at com.sun.tools.javac.tree.JCTree$JCVariableDecl.accept(JCTree.java:1084)
	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:92)

**To Reproduce**

I have a file with some fied annotatted with Getter and Setter. Issue reproduced once I add javadoc comment above this field or just open file with such comment already exist

**Expected behavior**
No exception

**Version info (please complete the following information):**
 - Lombok version 1.18.38 from gradle dependency
 - Platform Netbeans

**Additional context**
Product Version: Apache NetBeans IDE DEV (Build dev-cd3f7299071d4753b1c4999d87db77eb8a64a04f)
Java: 17.0.10; OpenJDK 64-Bit Server VM 17.0.10+13-LTS

**Comment by tmulle** [comment]
I have the same issue and reported it to Netbeans..
Although my example I don't have any Javadoc in my code yet and getting the error.

https://github.com/apache/netbeans/issues/8837

**Comment by matthiasblaesing** [comment]
General advice: keep Lombok up-to-date and ensure that the lombok version you used is compatible with the java compiler you are using. See: https://github.com/apache/netbeans/discussions/8221

**Comment by tmulle** [comment]
@matthiasblaesing I was using the latest version of Lombok.. 1.18.40 also. Still same error with JDk 21 and NetBeans 27.
Reverting back to lombok 1.18.36 fixes the issue.

Something in 1.18.38 and 1.18.40 breaks NetBeans 27 and JDK21 parsing.

Actually, even though compiling now works with 1.18.36 in NetBeans 27, I still see warnings in the files in the IDE saying:
```
Can't initialize javac processor due to (most likely) a class loader problem: java.lang.NoClassDefFoundError: Could not initialize class lombok.javac.Javac
  	at lombok.javac.apt.LombokProcessor.placePostCompileAndDontMakeForceRoundDummiesHook(LombokProcessor.java:174)
  	at lombok.javac.apt.LombokProcessor.init(LombokProcessor.java:96)
  	at lombok.core.AnnotationProcessor$JavacDescriptor.want(AnnotationProcessor.java:160)
  	at lombok.core.AnnotationProcessor.init(AnnotationProcessor.java:213)
  	at lombok.launch.AnnotationProcessorHider$AnnotationProcessor.init(AnnotationProcessor.java:64)
  	at org.netbeans.modules.java.source.indexing.APTUtils$ErrorToleratingProcessor.init(APTUtils.java:995)
```

I see there was a PR accepted which says it fixes the original error..do we have a timeframe on a new release?

**Comment by tmulle** [comment]
@rspiker @matthiasblaesing I was able to compile the "master" branch of lombok which created a `lombok-1.18.41.jar`. I installed that into my local maven repo and tested that with NetBeans 27 and JDK 21 and it appears to have fixed the issues now.

**Comment by rspilker** [comment]
We've already [released 1.18.42](https://central.sonatype.com/artifact/org.projectlombok/lombok/1.18.42) containing the fix.
