### ISSUE TITLE
[BUG] Eclipse 2023-03 regress - lombok.config not found

### ISSUE THREAD

**Issue by RedeemerSK** [projectlombok/lombok#3386]
**Describe the bug**
After updating Eclipse IDE for JEE developers to 2023-03 I noticed that lombok started to generate bytecode without considering my custom configuration in lombok.config file.

**To Reproduce**
Install Eclipse IDE version 2023-03, any version for Java development. Install lombok into this Eclipse installation. Extract [eclipse_2023-03_lombok_config_test.zip](https://github.com/projectlombok/lombok/files/11081373/eclipse_2023-03_lombok_config_test.zip). Import project as Maven project from extracted directory. See compilation errors caused by setters generated by lombok not having expected names (as configured in lombok.properties file).

**Expected behavior**
Lombok should consider custom configuration in lombok.config file.

**Version info (please complete the following information):**
 - Lombok version: 1.18.26
 - Platform:  Eclipse IDE for Enterprise Java and Web Developers (includes Incubating components), Version: 2023-03 (4.27.0), Build id: 20230309-1520 (fresh install) ... running on Eclipse Adoptium jdk-17.0.3.7-hotspot on Win 10. 

**Additional context**
Very quick debugging I did showed different behavior at lombok.eclipse.EclipseAST@111 when running Eclipse 2022-12 vs. 2023-03: in latest Eclipse, it takes the 'skipEclipseWorkspaceBasedFileResolver' (field value is true) code path, thus resolves path of compilation unit to "C:\\{path_within_eclipse_workspace}" (placeholders used, not literal value) which is IMHO invalid and causing lombok.config file to not be found in Eclipse project.

**Comment by janrieke** [comment]
Duplicate of #3332

**Comment by RedeemerSK** [comment]
> Duplicate of #3332

Sorry, my bad. I searched only open issues for duplicates.
