### ISSUE TITLE
[BUG] Lombok Does not work with IntelliJ IDEA 2023.1.1 (Community Edition)

### ISSUE THREAD

**Issue by g-viet** [projectlombok/lombok#3449]
**Describe the bug**
Compiling projects with Lombok in IntelliJ IDEA 2023.1.1 (Community Edition) leads to:
```
java: You aren't using a compiler supported by lombok, so lombok will not work and has been disabled.
  Your processor is: com.sun.proxy.$Proxy8
  Lombok supports: sun/apple javac 1.6, ECJ
```

**To Reproduce**
Any project using Lombok compiled in IntelliJ is affected.

**Version info (please complete the following information):**
Lombok version: 1.16.20
IntelliJ IDEA 2023.1.1 (Community Edition)
javac 1.8.0_372

**Additional context**
En example about another error message:
```
Code:
@AllArgsConstructor(onConstructor = @__(@Inject))
Error message:
java: cannot find symbol
  symbol: class __
```

And I tried to add `-Djps.track.ap.dependencies=false` but it leads to another error:
```
java: JPS incremental annotation processing is disabled. Compilation results on partial recompilation may be inaccurate. Use build process "jps.track.ap.dependencies" VM flag to enable/disable incremental annotation processing environment.
```

**Comment by dstango** [comment]
How about updating to the current lombok Version 1.18.28? The lombok version you mention is from 2020...

**Comment by 4ucl** [comment]
+1

**Comment by g-viet** [comment]
@dstango Thank you so much for your response.
This error is disappear 🎉 , but the build error is still displaying.
```
java: You aren't using a compiler supported by lombok, so lombok will not work and has been disabled.
  Your processor is: com.sun.proxy.$Proxy8
  Lombok supports: sun/apple javac 1.6, ECJ
```

The build error like:
```
Code:
@AllArgsConstructor(onConstructor = @__(@Inject))

Error message:
java: cannot find symbol
  symbol: class __
```

**Comment by g-viet** [comment]
Anyway, build this project on command line with `ant` or `ant compile` works well.
I dont know why it failed on IntelliJ

**Comment by dstango** [comment]
AFAIK IntelliJ comes bundled with the Eclipse Compiler. In Eclipse either 2022-12 or 2023-03 there were some internal changes with regards to the compiler, that resulted in breaks of lombok (you might search the issues to find out more). This has been fixed in the meantime in lombok, but you're probably "between the chairs" with IntelliJ 2023.1.1 -- it might be IntelliJ uses a newer Eclipse compiler version, but is still stuck with an older lombok version.
Probably you'll have to ask Jetbrains about that.

Maybe an update of the IntellJ plugin might help:
* https://projectlombok.org/setup/intellij
* https://plugins.jetbrains.com/plugin/6317-lombok/versions/stable/354419

It looks like you might have to wait for 2023.2, or get hold of an eap-version.

Can't help more, though, as I'm using Eclipse ;-) ...

**Comment by madhavgupta2011** [comment]
Hi, Maybe this might?
https://stackoverflow.com/questions/35496115/javadoc-error-on-requiredargsconstructoronconstructor-inject

**Comment by g-viet** [comment]
Thank you so much @dstango 
My environment:
Lombok version: 1.16.20
IntelliJ IDEA 2023.1.1 (Community Edition)
Compiler: javac
Openjdk version: 1.8.0_372
Apache Ant(TM) version 1.10.13 compiled on January 4 2023

**Comment by Rawi01** [comment]
@g-viet You use the old javac7 syntax for [onX](https://projectlombok.org/features/experimental/onX). The right one should be `@AllArgsConstructor(onConstructor_ = {@Inject})`

**Comment by g-viet** [comment]
@Rawi01 Thank you so much. If I use `@AllArgsConstructor(onConstructor_ = {@Inject})`, it leads another error like below:
```
java: cannot find symbol
  symbol:   method onConstructor_()
  location: @interface lombok.AllArgsConstructor
```

**Comment by g-viet** [comment]
@Rawi01 when I try to reference to `onConstructor_` but got this tool tip: `Cannot find declaration to go to`

**Comment by g-viet** [comment]
And Lombok plugin is shown on `Non-Bundled Plugins` (click `About IntelliJ IDEA` then click `Copy and Close`).
It works on my colleagues's PC and Lombok is not shown on `Non-Bundled Plugins`.

My IntelliJ IDEA about:
```
IntelliJ IDEA 2023.2.1 (Community Edition)
Build #IC-232.9559.62, built on August 23, 2023
Runtime version: 17.0.8+7-b1000.8 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.5.1
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Metal Rendering is ON
Registry:
    ide.experimental.ui=true

Non-Bundled Plugins:
    Lombook Plugin (232.9559.34)

Kotlin: 232-1.9.0-IJ9559.62
```

Here is on my colleagues's PC:
```
IntelliJ IDEA 2023.1.2 (Community Edition)
Build #IC-231.9011.34, built on May 16, 2023
Runtime version: 17.0.6+10-b829.9 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.4
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Non-Bundled Plugins:
    QAPlug (1.3.31)
    org.jetbrains.kotlin (231-1.9.0-release-358-IJ8770.65)
    com.dguner.lombok-builder-helper (1.5.0)
    org.intellij.scala (2023.1.19)
    QAPlug - FindBugs (1.3.10)

Kotlin: 231-1.9.0-release-358-IJ8770.65
```

Just dont know why !

**Comment by dstango** [comment]
Looks like idea has removed the Lombok plugin from the community edition as a default. Probably your colleague has upgraded his version and this kept a formerly available Plugin, while you might have done a fresh install.

There's an issue or PR referencing changes in the IntelliJ psychiatry of them community edition, if you search for it.

**Comment by g-viet** [comment]
I asked IntelliJ too.
Anyway after OS upgrading & clear all of them and try to install again from 0. It's fixed.
I dont know what happened, but the problem is gone, so I close this.

**Comment by rzwitserloot** [comment]
Yup, nothing we can do about this. Works fine in the code we are responsible for.

**Comment by Gaurav560** [comment]
C:\Users\gshar\IdeaProjects\JobApp\src\main\java\com\telusko\Job\impl\JobServiceImpl.java:24:4
java: cannot find symbol
  symbol:   method setId(int)
  location: variable job of type com.telusko.Job.Job

 I am also unable to start my spring boot application.The error states that it is not able to find a setter method for my class field
