### PR TITLE
Fix duplicate annotations in Eclipse when copying Jackson annotations

### LINKED ISSUE #3934: [BUG] com.fasterxml.jackson.annotation.JsonProperty is not a repeatable annotation interface
**Describe the bug**

We have a class that looks like this:
```
@Value
@Accessors(fluent = true)
@NoArgsConstructor(force = true, access = AccessLevel.PRIVATE)
@AllArgsConstructor
@Getter(onMethod = @__(@JsonProperty))
public class ListMeta {
  @JsonProperty("continue")
  private final String continue_;
}
```

This worked fine in 1.18.38, but updating to 1.18.40 we get

```
ListMeta.java:[14,24] com.fasterxml.jackson.annotation.JsonProperty is not a repeatable annotation interface
``` 

**Expected behavior**
It should work as before. 🙂

**Version info (please complete the following information):**
Lombok 1.18.40

### PR DESCRIPTION
**Pull request by janrieke**
This PR fixes a bug introduced by #3860: With `lombok.copyJacksonAnnotationsToAccessors = true`, some annotation are copied twice in Eclipse, resulting in the compilation error "`@XYZ is not a repeatable annotation`".

Fixes #3934.

### CODE REVIEW

**Comment by fbricon** [comment]
Can someone please review this PR? The problem affects vscode-java (as it runs a version of Eclipse JDT under the hood)

**Comment by pastouret** [comment]
> Can someone please review this PR? The problem affects vscode-java (as it runs a version of Eclipse JDT under the hood)

+1 a retro-compatible fix is highly welcome for all the vscoders trying to do some java

**Comment by erizzo** [comment]
Please review this contribution from the community. Sorry to tag committers directly but Lombok in Eclipse-based and VS Code IDEs is broken without it.
@Rawi01 @rzwitserloot @liampace @rspilker

**Comment by pastouret** [comment]
For anyone ending up here because of the same issue I'm sharing my workaround.
Add into a `lombok.config` this line `lombok.copyJacksonAnnotationsToAccessors = false`

**Comment by giacgbj** [comment]
Can you approve this one and fix this behavior?

**Comment by pastouret** [comment]
+1 Could we have visibility on this PR review? Vscoders are still stuck

**Comment by rhuitl** [comment]
Can we get some traction on this PR please? `lombok.copyJacksonAnnotationsToAccessors = false` is not a viable workaround for everybody, and not being able to run in VS Code is... meh.

**Comment by nealeu** [comment]
I feel your pain. Lack of feedback from maintainers (I've had zero on JSpecify, a build perf fix, and on discussion forum about Lombok 2.0 thoughts) is really having me consider a community fork. It's been an admirable effort over the years - deserving of retirement level income, but I think we really need a wider set of committers and time commitment.  

I've got a really hacking Jitpack setup for getting my PRs into my own JARs, but I think that could be really cleaned up with a modern build so people can use IntelliJ, and target JDK 17+.

**Comment by rzwitserloot** [comment]
At jobbyjob I'm very happy with the [Lean Branching](https://github.com/fork-dev/TrackerWin/issues/1432) model, but github makes a total hash of it. They also seem to make a hash of merging pull requests (probably my fault). Point is, I'm merging this stuff in a way that confuses github.

This has been merged.
